### ISSUE TITLE
How to handle degenerate primer sets?

### ISSUE THREAD

**Issue by aretchless** [ncezid-biome/HMAS-QC-Pipeline2#1]
Thank you for sharing this tool. We're interested in testing it for our multi-amplicon multi-family viral assay. Our assay includes degenerate primer sets -- how should those be encoded in the primer file? Should we use degenerate base codes, or should be spell out each of the possible primers and each of the possible combination of primers (or something else)?

**Comment by jinfinance** [comment]
Hi,

Thanks for the question. We too use degenerate primer sets.  There is no need to spell them out.  If you take a look at our sample primer_pair list under: 
test_data/451_subset_primer_pairs

primer	TGYTAACGGCAGATGCGAGCA	AATCTCCAGACCATGCCAGTG	OG0003312primerGroup2
primer	GARGAGGGGTTTCAGCGTTGC	YCGGTAAGTATCGCCAGGATA	OG0002693primerGroup6

We use cutadapt to trim the primers and cutadapt supports IUPAC nucleotide codes.

**Comment by aretchless** [comment]
Thanks!
